import * as Illustrations from "./illustrations";

export const illustrationsMapped = {
  devices: Illustrations.Devices,
  draw: Illustrations.Draw,
  error404: Illustrations.Error404,
  gift: Illustrations.Gift,
  graph: Illustrations.Graph,
  logo: Illustrations.Logo,
  logoSmall: Illustrations.LogoSmall,
  logoWhite: Illustrations.LogoWhite,
  pixelsBottomDark: Illustrations.PixelsBottomDark,
  pixelsBottomLight: Illustrations.PixelsBottomLight,
  pixelsBottomMedium: Illustrations.PixelsBottomMedium,
  PixelsTopDark: Illustrations.PixelsTopDark,
  pixelsTopLight: Illustrations.PixelsTopLight,
  pixelsTopMedium: Illustrations.PixelsTopMedium,
  points: Illustrations.Points,
  report: Illustrations.Report,
  saveMoney: Illustrations.SaveMoney,
  security: Illustrations.Security,
  settings: Illustrations.Settings,
  signIn: Illustrations.SignIn,
  transaction: Illustrations.Transaction,
};
